services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: npm install && npm build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.12.1
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: strapi
    plan: starter